#!/bin/sh
set -ue
cd $AUTOPKGTEST_TMP

DEB_HOST_MULTIARCH=$(dpkg-architecture -q DEB_HOST_MULTIARCH)

# Enforce the BLAS (resp. LAPACK) contained in package libblas3 (resp. liblapack3)
export LD_LIBRARY_PATH=/usr/lib/${DEB_HOST_MULTIARCH}/blas:/usr/lib/${DEB_HOST_MULTIARCH}/lapack

cat << EOF > tmp.c
#include <stdio.h>
#include <lapacke.h>
void LAPACKE_xerbla( const char *name, lapack_int info )
{
    if( info < 0 ) { 
        printf( "OVERRIDE SUCCESSFUL override %d in %s\n", -(int) info, name );
    }   
}


int main (int argc, const char * argv[])
{
   double a[5][3] = {1,1,1,2,3,4,3,5,2,4,2,5,5,4,3};
   double b[5][2] = {-10,-3,12,14,14,12,16,16,18,16};
   lapack_int info,m,n,lda,ldb,nrhs;
   int i,j;

   m = 5;
   n = 9;
   nrhs = 2;
   lda = 3;
   ldb = 2;

   info = LAPACKE_dgels(LAPACK_ROW_MAJOR,'N',m,n,nrhs,*a,lda,*b,ldb);
   return(info);
}
EOF
gcc tmp.c -llapacke
./a.out 2>&1 | grep "OVERRIDE SUCCESSFUL"

