#!/usr/bin/dh-exec

libblas64.so usr/lib/${DEB_HOST_MULTIARCH}/blas64/
static-64/libblas.a => usr/lib/${DEB_HOST_MULTIARCH}/blas64/libblas64.a
CBLAS/include/cblas.h => usr/include/${DEB_HOST_MULTIARCH}/cblas64-netlib.h
CBLAS/include/cblas_mangling.h => usr/include/${DEB_HOST_MULTIARCH}/cblas64_mangling.h
CBLAS/include/cblas_f77.h => usr/include/${DEB_HOST_MULTIARCH}/cblas64_f77.h
BLAS/blas64-netlib.pc usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig/
