#!/usr/bin/dh-exec

libblas64.so usr/lib/${DEB_HOST_MULTIARCH}/blas64/
static-64/libblas.a => usr/lib/${DEB_HOST_MULTIARCH}/blas64/libblas64.a
#CBLAS/include/cblas.h => usr/include/${DEB_HOST_MULTIARCH}/cblas-netlib.h
#CBLAS/include/cblas_mangling.h usr/include/${DEB_HOST_MULTIARCH}/
#CBLAS/include/cblas_f77.h usr/include/${DEB_HOST_MULTIARCH}/
BLAS/blas64-netlib.pc usr/lib/${DEB_HOST_MULTIARCH}/pkgconfig/
